apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-aci-deployment
spec:
  replicas: 5
  selector:
      matchLabels:
        app: helloworld-aci
  template:
    metadata:
      labels:
        app: helloworld-aci
    spec:
      containers:
      - name: helloworld-aci
        image: <yourACRRegistry.azurecr.io>/helloworld:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: <k8sSecretName>
      nodeSelector:
          kubernetes.io/role: agent
          beta.kubernetes.io/os: linux
          type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-aci
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30306
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-aci
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-aci-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: demok8s.example.com
    http:
      paths:
      - path: /aci
        backend:
          serviceName: helloworld-aci
          servicePort: http
