apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: helloworld-internal
    spec:
      containers:
      - name: k8s-demo
        image: <yourACRRegistry.azurecr.io>/helloworld:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: <k8sSecretName>
      nodeSelector:
          kubernetes.io/role: agent
          beta.kubernetes.io/os: linux
          type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "services"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30304
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-internal
