apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v1-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-v1
    spec:
      containers:
      - name: k8s-demo
        image: <yourACRRegistry.azurecr.io/helloworld:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: <k8sSecretName>
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-v1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30303
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-v1-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /v1
        backend:
          serviceName: helloworld-v1
          servicePort: http
