apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-v2-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-v2
    spec:
      containers:
      - name: k8s-demo
        image: kumar.azurecr.io/helloworld:2
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-v2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30304
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-v2
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-v2-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: demo.cyborg.ml
    http:
      paths:
      - path: /v2
        backend:
          serviceName: helloworld-v2
          servicePort: http
